- chronos.cabal
- src/Chronos/Internal/CTimespec.hs
- src/cbits/hs-time.c
`clock_gettime` doesnt exist on macos. Therefore I had to fake it using time of day. You should review this code my c is rusty.
Also can I have write access?
> macos support

- bench/Bench.hs
- chronos.cabal
- src/Chronos.hs
This PR implements a time parsing benchmark for UtcTime. Chronos does *very* well:
```
benchmarking parsing/Thyme.parseTime
time                 1.329 μs   (1.312 μs .. 1.354 μs)
0.996 R²   (0.992 R² .. 0.999 R²)
mean                 1.341 μs   (1.318 μs .. 1.381 μs)
std dev              101.7 ns   (69.75 ns .. 138.8 ns)
variance introduced by outliers: 82% (severely inflated)
benchmarking parsing/Time.parseTimeM
time                 2.864 μs   (2.853 μs .. 2.876 μs)
1.000 R²   (1.000 R² .. 1.000 R²)
mean                 2.858 μs   (2.850 μs .. 2.874 μs)
std dev              38.22 ns   (22.48 ns .. 63.50 ns)
variance introduced by outliers: 11% (moderately inflated)
benchmarking parsing/Thyme.timeParser
time                 939.6 ns   (935.8 ns .. 943.0 ns)
1.000 R²   (1.000 R² .. 1.000 …
```
> Implement parsing benchmark

- bench/Bench.hs
- chronos.cabal
- src/Chronos.hs
I've always wondered about Zepto. Turns out it is fast:
```
Benchmark bench: RUNNING...
benchmarking parsing/Time.parseTimeM
time                 8.935 μs   (8.447 μs .. 9.549 μs)
0.983 R²   (0.972 R² .. 0.998 R²)
mean                 8.538 μs   (8.367 μs .. 8.900 μs)
std dev              764.0 ns   (464.9 ns .. 1.190 μs)
variance introduced by outliers: 84% (severely inflated)
benchmarking parsing/Thyme.parseTime
time                 1.770 μs   (1.678 μs .. 1.851 μs)
0.989 R²   (0.985 R² .. 0.996 R²)
mean                 1.675 μs   (1.641 μs .. 1.720 μs)
std dev              125.4 ns   (83.81 ns .. 171.0 ns)
variance introduced by outliers: 81% (severely inflated)
benchmarking parsing/Thyme.timeParser
time                 1.042 μs   (1.009 μs .. 1.088 μs)
0.990 R²   (0.985 R² .. 0.996 …
```
> Zepto performance wins

- bench/Bench.hs
- chronos.cabal
This is related to #22 
I am not sure at all about the `Chronos` use, in particular where to put the `dayToDate` or `Chronos.timeToDatetime` conversion . Do we need to take into account these conversions in the benchmark time ?
Otherwise, I am benchmarking two pretty functions:
* Dmy: or Days Month Year
* HMS: or Hour Minutes Seconds
> Add benchmarks for pretty-print

- README.markdown
Benchmarks were implemented in #24. This PR adds results of the benchmarks to README file. I think it's useful to make the results visible. I just peformed benchmarks on my working machine and inserted table inside README.
> [#22] Add benchmark results to README

- chronos.cabal
I was able to build without difficulty on the latest `semigroups` (0.19.1).
> Bump semigroups bound.

- CHANGELOG.md
- chronos.cabal
- src/Chronos.hs
this PR drops clock on newer GHCs, in favour of getMonotonicTimeNSec.
resolves #29
> drop clock on newer GHCs

- src/Chronos.hs
Necessary since #36 on Windows, at least in GHC 8.6.3
> enable RecordWildCards in Chronos.hs

- src/Chronos.hs
- test/Spec.hs
This commit adds the following exposed functions:
```
parser_Ymd_lenient :: Parser Date
parser_Dmy_lenient :: Parser Date
parser_Mdy_lenient :: Parser Date
parser_DmyHMS_lenient :: Parser Datetime
parser_DmyHMS_opt_S_lenient :: Parser Datetime
parser_MdyHMS :: DatetimeFormat -> Parser Datetime
parser_MdyHMS_lenient :: Parser Datetime
parser_MdyHMS_opt_S :: DatetimeFormat -> Parser Datetime
parser_MdyHMS_opt_S_lenient :: Parser Datetime
parser_YmdHMS_lenient :: Parser Datetime
parser_YmdHMS_opt_S_lenient :: Parser Datetime
decode_DmyHMS_lenient :: Text -> Maybe Datetime
decode_DmyHMS_opt_S_lenient :: Text -> Maybe Datetime
decode_MdyHMS :: DatetimeFormat -> Text -> Maybe Datetime
decode_MdyHMS_lenient :: Text -> Maybe Datetime
decode_MdyHMS_opt_S :: DatetimeFormat -> Text -> Maybe Datetime …
```
> Adds Lenient versions of Datetime parsers and decoders

- README.markdown
- appveyor.yml
Resolves #42
This PR adds the config file. In order to actually turn on Appveyor for the repository you should actually sign in at appveyor.com and to add `chronos`. Here are the docs that should help: https://www.appveyor.com/docs/
Let me know if you have any questions or comments about this.
> [#42] Add Appveyor config

- bench/Bench.hs
I wanted to compare the YmdHMS parsing/formatting for a post I'm writing about time libraries so I needed to add this, figured you may want it.
This benchmark saved me a bunch of time, basically exactly what I wanted to check! :1st_place_medal:
> Add benchmark for pretty printing YmdHMS

- CHANGELOG.md
- chronos.cabal
- src/Chronos.hs
- test/Spec.hs
This converts from a datetime to a day of week account for leap year. Also, adds todayDayOfWeek, yesterdayDayOfWeek, and tomorrowDayOfWeek. Originally, this work was at https://github.com/andrewthad/chronos/pull/49. This PR is the same thing but squashed and rebased for a cleaner git history.
Algorithm for datetime conversion adapted from:
https://cs.uwaterloo.ca/~alopez-o/math-faq/node73.html
Algorithm for nanoseconds-since-epoch conversion adapted from:
https://stackoverflow.com/q/36357013/1405768
> Implement timeToDayOfWeek and datetimeToDayOfWeek

- bench/Bench.hs
I realized the parsing benchmarks weren't completely fair as they didn't pay for converting to the tight POSIX representation, so I have fixed that.
I reran the benchmarks and it barely made a difference though, it's the string munging which requires all the work.
Can understand if you don't want to merge though, maybe this _is_ the use case that you are thinking of.
> Benchmark should convert to the tight rep to be fair

- src/Chronos/Internal/CTimespec.hs
it's pretty straightforward – `CTimespec` is defined in an `#else` if `ghcjs_HOST_OS` is not defined.
> don't export undefined CTimespec on ghcjs

- chronos.cabal
- src/Chronos.hs
Hi,
Here is a pull request that corrects the month for the windows build. 
Also a very minor thing, but should datetimeFromYmdhms return zero instead of one when the month is out of range?
...
mx = if m >= 1 && m <= 12
then fromIntegral (m - 1)
else 1  --- should this be zero instead?
...
Best,
Grant
> fix month off by one for windows: add torsor to test dependencies

- chronos.cabal
I increased the bounds for all packages that had newer versions and tested with 8.10.4. However, the doctest suite fails to compile, finding none of the imports in `Chronos.hs`. Any advice?
> bump dependency bounds for aeson and attoparsec

- chronos.cabal
- src/Chronos/Internal/FastText.hs
chronos doesn't seem to be affected by the breaking changes in the text 2.0 package. There is only `Chronos.Internal.FastText` module that uses some internal functions where the behavious may have changed. But `FastText` doesn't seem to be used anywhere, isn't exported publically and isn't tested.
> Support text 2

- chronos.cabal
Hello,
could you please accept this bump to upper bounds?
The current bound is too restrictive and doesn't allow building with semigroups 0.20 present in stackage nightly (https://www.stackage.org/nightly-2022-10-24/package/semigroups-0.20).
Thank you for your consideration.
> Bump upper bound for semigroups

- chronos.cabal
```
❯ cabal build --constraint="primitive == 0.8.0.0" --allow-newer=bytesmith:primitive --allow-newer=wide-word:primitive --allow-newer=run-st:primitive --allow-newer=primitive-unlifted:primitive --allow-newer=contiguous:primitive --allow-newer=byteslice:primitive --allow-newer=tuples:primitive --allow-newer=primitive-addr:primitive --allow-newer=bytebuild:primitive --allow-newer=aeson:primitive
Resolving dependencies...
Build profile: -w ghc-9.4.4 -O1
In order, the following will be built (use -v for more details):
- bytebuild-0.3.12.0 (lib) (requires build)
- bytesmith-0.3.9.1 (lib) (requires build)
- semigroups-0.20 (lib) (requires build)
- torsor-0.1 (lib) (requires build)
- chronos-1.1.5 (lib) (first run)
Starting     semigroups-0.20 (lib)
Starting     torsor-0.1 (lib)
Starting …
```
> build with primitive 0.8

- chronos.cabal
Build and tests succeed with ghc 9.6.2 with
- git: https://github.com/byteverse/bytebuild.git commit: 32034ac3232130a81879db022a38024b8e0ab27c
- git: https://github.com/costarastrology/zigzag.git commit: 63c417592e36d163d1992553d142bd09615d7f72
> Allow base 4.18

- CHANGELOG.md
- src/Chronos.hs
@chessai I've taken the liberty of filling in the next release's changelog. Please tell me if the numbers are not correct.
> Add `sinceEpoch` and `asSeconds`

- .github/dependabot.yml
- .github/workflows/ci.yml
- chronos.cabal
- src/Chronos.hs
- src/Chronos/Internal/CTimespec.hs
This PR introduces a GitHub Action matrix that tests GHC versions from 8.10.7 to 9.8.1, based on the `tested-with` metadata from the cabal file.
It supersedes #86
> Support GHC 8.10 to 9.8
